# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-23 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photologue_custom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyGallery',
        ),
        migrations.DeleteModel(
            name='MyPhoto',
        ),
    ]
