# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('photologue', '0010_auto_20160105_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Title')),
                ('slug', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('text', models.TextField(verbose_name='Text')),
                ('image_caption', models.CharField(blank=True, max_length=50, null=True, verbose_name='caption')),
                ('image_description', models.TextField(blank=True, null=True, verbose_name='Image Text')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Introduction',
            },
        ),
    ]
