# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='image_caption',
            field=models.CharField(blank=True, max_length=50, verbose_name='caption'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo'),
        ),
    ]
