# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-31 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0002_auto_20171031_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='image_description',
            field=models.TextField(blank=True, null=True, verbose_name='Image Text'),
        ),
    ]
