# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0003_introduction_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='slug',
            field=models.CharField(default='title', max_length=200, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Title'),
        ),
    ]
