# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0004_auto_20171101_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='image_caption',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='caption'),
        ),
    ]
