# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0005_auto_20171101_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='slug',
            field=models.CharField(default=models.CharField(max_length=200, unique=True, verbose_name='Title'), max_length=200, verbose_name='slug'),
        ),
    ]
