# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-10 13:47
from __future__ import unicode_literals
from django.conf import settings

from django.db import migrations


def change_site_name(apps, schema_editor):
	sites = apps.get_model('sites.Site')
	site = sites.objects.get(id=settings.SITE_ID)
	site.name = 'localhost'
	site.domain = 'localhost:8000'
	site.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
	migrations.RunPython(change_site_name),
    ]
