# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import zinnia.models_bases.entry


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Galleries',
                'verbose_name': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('image', models.ImageField(blank=True, help_text='Used for illustration.', upload_to=zinnia.models_bases.entry.image_upload_to_dispatcher, verbose_name='image')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='pictures',
            field=models.ManyToManyField(to='zinnia_gallery.Picture'),
        ),
    ]
