# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0002_auto_20171030_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zinnia_gallery.Picture'),
        ),
    ]
