# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0003_auto_20171030_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Photo'),
        ),
    ]
